package io.github.darvld.granite

/**
 * A marker that binds a [Component] ID with its corresponding data type.
 *
 * This interface is not meant to be implemented manually; instead, the Granite compiler plugin will automatically
 * use it in a synthetic companion object for every class annotated with [ComponentData].
 *
 * Manual implementations are technically allowed but custom [type] accessors will be replaced at compile-time by
 * the plugin, to ensure a valid ID is used for the component.
 *
 * @see ComponentData
 */
public interface ComponentType<T : Any> {
  /**
   * The [Component] described by this type; data held by this component will have the type [T].
   *
   * Implementing this property does nothing, as the compiler plugin will replace it with a synthetic accessor to
   * ensure the consistency of component IDs.
   *
   * @see ComponentData
   */
  public val type: Component
    get() = error("Component identifier should be generated by the compiler plugin, check your project settings")
}