package io.github.darvld.granite.plugin.frontend.k2

import org.jetbrains.kotlin.GeneratedDeclarationKey

/** A marker used to identify synthetic declarations generated by the plugin. */
object ComponentPluginKey : GeneratedDeclarationKey() {
  override fun toString(): String = "GraniteComponentsPlugin"
}