on:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Run all tests
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    env:
      BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}

    permissions:
      checks: "write"
      pull-requests: "write"
    
    steps:
      - uses: actions/checkout@v3

      # use JDK 21+
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # prepare codebase (build pre-pass)
      - name: Prepare
        run: make prepare-plugins
      
      # run tests
      - name: Test
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: test
      